// <auto-generated />
using System;
using Hook.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchStarter.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407142913_AddPaymentPermissions")]
    partial class AddPaymentPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hook.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297",
                            ConcurrencyStamp = "d1c8e5b9-9f0a-4c3e-8a1b-2f5e6d7c8a9b",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9",
                            ConcurrencyStamp = "f3a7b8c9-0d2e-4f5a-9b3c-4d6e7f8a9b1c",
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "42bf2b74-278d-453f-acd7-52d09bbcdcb3",
                            ConcurrencyStamp = "e6253d46-e8bc-454e-9846-8b4513db68cc",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "BoatOwner",
                            NormalizedName = "BOATOWNER"
                        });
                });

            modelBuilder.Entity("Hook.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "877a5585-4894-4f4b-8989-f45476063ce1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a25eba83-ab00-408b-8dfa-ce8a1cf37bea",
                            Email = "AdminAccount@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsDisabled = false,
                            LastName = "Account",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINACCOUNT@GMAIL.COM",
                            NormalizedUserName = "ADMINACCOUNT@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIoxWb26cTzdfCumxCiMdXzQAS4fntJbgyxCwE8JfNYexufyjyYGQL4kmp0ydKXiJA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "CFFCC4EEB0EE4D608E7CEFFE61FFDBD2",
                            TwoFactorEnabled = false,
                            UserName = "AdminAccount@gmail.com"
                        });
                });

            modelBuilder.Entity("Hook.Domain.Entities.Boat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("OwnerProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerProfileId");

                    b.ToTable("Boats");
                });

            modelBuilder.Entity("Hook.Domain.Entities.BoatImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoatId");

                    b.ToTable("BoatImages");
                });

            modelBuilder.Entity("Hook.Domain.Entities.BoatOwnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminRejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoatLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BoatLicensePhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalIdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalIdPhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BoatLicenseNumber")
                        .IsUnique();

                    b.HasIndex("NationalIdNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BoatOwnerProfiles");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfParticipants")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TripDateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TripDateId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("[BookingId] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId", "TripId")
                        .IsUnique();

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "Rating >= 1 AND Rating <= 5");
                        });
                });

            modelBuilder.Entity("Hook.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BoatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasEquipmentRental")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSnorkeling")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGuided")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TripManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoatId");

                    b.HasIndex("TripManagerId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Hook.Domain.Entities.TripDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripDates", t =>
                        {
                            t.HasCheckConstraint("CK_TripDate_Dates", "EndDate > StartDate");
                        });
                });

            modelBuilder.Entity("Hook.Domain.Entities.TripImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripImages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ViewProfile",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.UpdateProfile",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ChangePassword",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ViewAll",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ManageRoles",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Roles.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Roles.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Roles.Update",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Roles.ToggleActive",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.BoatOwner.Apply",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.BoatOwner.ViewProfile",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.BoatOwner.ViewAll",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.BoatOwner.UpdateStatus",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.BoatOwner.Delete",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.BoatOwner.Restore",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.Update",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.Delete",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.Restore",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.Update",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.Delete",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.Restore",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.UpdateStatus",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.Cancel",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.ViewAll",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.UploadReceipt",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.Verify",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.ViewAll",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.Stats",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ViewProfile",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.UpdateProfile",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ChangePassword",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.BoatOwner.Apply",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.BoatOwner.ViewProfile",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.View",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 43,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.View",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 44,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.View",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 45,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.Create",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 46,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.Cancel",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 47,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.View",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 48,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.UploadReceipt",
                            RoleId = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9"
                        },
                        new
                        {
                            Id = 49,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ViewProfile",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 50,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.UpdateProfile",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 51,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ChangePassword",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 52,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.BoatOwner.ViewProfile",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 53,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.View",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 54,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.Create",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 55,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.Update",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 56,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Boats.Delete",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 57,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.View",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 58,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.Create",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 59,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.Update",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 60,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Trips.Delete",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 61,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.View",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 62,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.UpdateStatus",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 63,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.View",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 64,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.Verify",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        },
                        new
                        {
                            Id = 65,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.Stats",
                            RoleId = "42bf2b74-278d-453f-acd7-52d09bbcdcb3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "877a5585-4894-4f4b-8989-f45476063ce1",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Hook.Domain.Entities.ApplicationUser", b =>
                {
                    b.OwnsMany("Hook.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Boat", b =>
                {
                    b.HasOne("Hook.Domain.Entities.BoatOwnerProfile", "OwnerProfile")
                        .WithMany("Boats")
                        .HasForeignKey("OwnerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerProfile");
                });

            modelBuilder.Entity("Hook.Domain.Entities.BoatImage", b =>
                {
                    b.HasOne("Hook.Domain.Entities.Boat", "Boat")
                        .WithMany("Images")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");
                });

            modelBuilder.Entity("Hook.Domain.Entities.BoatOwnerProfile", b =>
                {
                    b.HasOne("Hook.Domain.Entities.ApplicationUser", "User")
                        .WithOne("BoatOwnerProfile")
                        .HasForeignKey("Hook.Domain.Entities.BoatOwnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Hook.Domain.Entities.TripDate", "TripDate")
                        .WithMany("Bookings")
                        .HasForeignKey("TripDateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hook.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TripDate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Hook.Domain.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("Hook.Domain.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Review", b =>
                {
                    b.HasOne("Hook.Domain.Entities.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hook.Domain.Entities.Trip", "Trip")
                        .WithMany("Reviews")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hook.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Trip", b =>
                {
                    b.HasOne("Hook.Domain.Entities.Boat", "Boat")
                        .WithMany("Trips")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hook.Domain.Entities.BoatOwnerProfile", "TripManager")
                        .WithMany("ManagedTrips")
                        .HasForeignKey("TripManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Boat");

                    b.Navigation("TripManager");
                });

            modelBuilder.Entity("Hook.Domain.Entities.TripDate", b =>
                {
                    b.HasOne("Hook.Domain.Entities.Trip", "Trip")
                        .WithMany("TripDates")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Hook.Domain.Entities.TripImage", b =>
                {
                    b.HasOne("Hook.Domain.Entities.Trip", "Trip")
                        .WithMany("Images")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Hook.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Hook.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Hook.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Hook.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hook.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Hook.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hook.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("BoatOwnerProfile");

                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Boat", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Hook.Domain.Entities.BoatOwnerProfile", b =>
                {
                    b.Navigation("Boats");

                    b.Navigation("ManagedTrips");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Hook.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("TripDates");
                });

            modelBuilder.Entity("Hook.Domain.Entities.TripDate", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
